substitutions:
  device: iron

esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini

<<: !include base.yaml

binary_sensor:
  - platform: gpio
    pin: D3
    name: "${device}.button"

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

sensor:
  - platform: bmp280
    temperature:
      name: "${device}.temperature"
      oversampling: 8x
      accuracy_decimals: 2
    pressure:
      name: "${device}.pressure"
      oversampling: 8x
    address: 0x76
    update_interval: 15s

